var swaggerAutogen = require('swagger-autogen')()

var jsonSchema = require('mongoose-schema-jsonschema')();


var Topic = require('./models/topic');
var User = require('./models/user');


const doc = {
    info: {
        version: "1.0.0",
        title: "whyme API",
        description: "Documentation automatically generated by the <b>swagger-autogen</b> module."
    },
    host: "localhost:3999",
    basePath: "/",
    schemes: ['http'],
    consumes: ['application/json'],
    produces: ['application/json'],
    tags: [
        {
            "name": "Users",
            "description": "Endpoints"
        }
    ],
    securityDefinitions: {
        apiKeyAuth:{
            type: "apiKey",
            in: "header",       // can be "header", "query" or "cookie"
            name: "X-API-KEY",  // name of the header, query parameter or cookie
            description: "any description..."
        }
    },
    definitions: {
      Users : User.jsonSchema(),
      Topics : Topic.jsonSchema()
    },

    
}

const outputFile = './others/swagger_doc.json'
const endpointsFiles = ['./app.js']

swaggerAutogen(outputFile, endpointsFiles, doc).then(() => {
    require('./index')           // Your project's root file
})